name: dbook
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  # GetX
  get: ^4.6.5

  # 国际化
  intl: ^0.17.0

  # 屏幕适配
  flutter_screenutil: ^5.7.0

  # 下拉刷新
  pull_to_refresh_flutter3: ^2.0.1

  # toast
  fluttertoast: ^8.2.1

  # easy_loading
  flutter_easyloading: ^3.0.3

  # http
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1

  # 缓存
  get_storage: ^2.1.1
#  cached_network_image: ^3.2.0
#  flutter_cache_manager: ^3.3.0

  # 加密安全 SHA
#  crypto: ^3.0.1

  synchronized: ^3.0.0+2


  # 包信息
  package_info_plus: ^1.4.0

  # 路径查询
  path_provider: ^2.0.9

  # permission 权限
  permission_handler: ^10.2.0

  #网络状态
  connectivity: ^3.0.2

  # 日志
  logger: ^1.1.0

  # 网络图片加载
  extended_image: ^7.0.2

  web3dart: ^2.6.1
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0


  carousel_slider: ^4.2.1

  dbook_cryptology_plugin:
    git:
      url: git@github.com:onlyYU/dbook_cryptology_plugin.git


  lottie: ^1.4.3

  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3

  webview_flutter: ^3.0.1

  # 工具类
  common_utils: ^2.1.0

  # 添加提醒到本地日历
  add_2_calendar: ^2.2.3

  fl_chart: ^0.55.2

  html_editor_enhanced: ^2.5.1

#  file_picker: ^5.2.5

  image_picker: ^0.8.7

  flutter_picker: ^2.1.0

  flutter_datetime_picker: ^1.5.1

  connectivity_plus: ^2.3.9

  flutter_inappwebview: ^5.7.2+3

  web_socket_channel: ^2.3.0

  pdf: ^3.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # 启动页快捷生成
  flutter_native_splash: ^2.2.19

  # 快速生成app图标
  flutter_launcher_icons: ^0.12.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # ddid:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/svg/default_avatar/
    - assets/files/
#    - assets/images/logos/
#    - assets/images/backgrounds/

#  fonts:
#    - family: Avenir
#      fonts:
#        - asset: assets/fonts/Avenir-Book.ttf
#          weight: 400 # normal
#    - family: Montserrat
#      fonts:
#        - asset: assets/fonts/Montserrat-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Montserrat-SemiBold.ttf
#          weight: 600
#    - family: Iconfont
#      fonts:
#        - asset: assets/fonts/iconfont.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  #  flutter pub run flutter_launcher_icons:main